syntax = "proto3";
package ET;

message HttpGetRouterResponse
{
	repeated string Realms = 1;
	repeated string Routers = 2;
}

message RouterSync
{
	uint32 ConnectId = 1;
	string Address = 2;
}

// ResponseType M2C_TestResponse
message C2M_TestRequest // ILocationRequest
{
	int32 RpcId = 1;
	string request = 2;
}

message M2C_TestResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string response = 4;
}

// ResponseType G2C_EnterMap
message C2G_EnterMap // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_EnterMap // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	/// 自己的UnitId
	int64 MyId = 4;
}

message MoveInfo
{
	repeated Unity.Mathematics.float3 Points = 1;
	Unity.Mathematics.quaternion Rotation = 2;
	int32 TurnSpeed = 3;
}

message UnitInfo
{
	int64 UnitId = 1;
	string Name = 2;
	int32 ConfigId = 3;
	int32 Type = 4;
	int32 CampType = 5;
	int64 OwnerId = 6;
	int64 TeamId = 7;
	Unity.Mathematics.float3 Position = 8;
	Unity.Mathematics.float3 Forward = 9;
	map<int32, int64> KV = 10;
	MoveInfo MoveInfo = 11;
}

message M2C_CreateUnits // IMessage
{
	repeated UnitInfo Units = 1;
}

message M2C_CreateMyUnit // IMessage
{
	UnitInfo Unit = 1;
}

message M2C_StartSceneChange // IMessage
{
	int64 SceneInstanceId = 1;
	string SceneName = 2;
}

message M2C_RemoveUnits // IMessage
{
	repeated int64 Units = 1;
}

message C2M_PathfindingResult // ILocationMessage
{
	int32 RpcId = 1;
	Unity.Mathematics.float3 Position = 2;
}

message C2M_Stop // ILocationMessage
{
	int32 RpcId = 1;
}

message M2C_PathfindingResult // IMessage
{
	int64 Id = 1;
	Unity.Mathematics.float3 Position = 2;
	repeated Unity.Mathematics.float3 Points = 3;
}

message M2C_Stop // IMessage
{
	int32 Error = 1;
	int64 Id = 2;
	Unity.Mathematics.float3 Position = 3;
	Unity.Mathematics.quaternion Rotation = 4;
}

// ResponseType G2C_Ping
message C2G_Ping // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Ping // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}


message G2C_Test // ISessionMessage
{
}

// ResponseType M2C_Reload
message C2M_Reload // ISessionRequest
{
	int32 RpcId = 1;
	string Account = 2;
	string Password = 3;
}

message M2C_Reload // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType R2C_Login
message C2R_Login // ISessionRequest
{
	int32 RpcId = 1;
	string  Account = 2; // 帐号
	string  Password = 3; // 密码
}

message R2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string Address = 4;
	int64 Key = 5;
	int64 GateId = 6;
}

// ResponseType G2C_LoginGate
message C2G_LoginGate // ISessionRequest
{
	int32 RpcId = 1;
	int64 Key = 2; // 帐号
	int64 GateId = 3;
}

message G2C_LoginGate // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}

message G2C_TestHotfixMessage // ISessionMessage
{
	string Info = 1;
}

// ResponseType M2C_TestRobotCase
message C2M_TestRobotCase // ILocationRequest
{
	int32 RpcId = 1;
	int32 N = 2;
}

message M2C_TestRobotCase // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int32 N = 4;
}

message C2M_TestRobotCase2 // ILocationMessage
{
	int32 RpcId = 1;
	int32 N = 2;
}

message M2C_TestRobotCase2 // ILocationMessage
{
	int32 RpcId = 1;
	int32 N = 2;
}

// ResponseType M2C_TransferMap
message C2M_TransferMap // ILocationRequest
{
	int32 RpcId = 1;
	int32 MapConfigId = 1;
	//地图唯一ID(可选)
	int64 MapFiberId = 2;
}

message M2C_TransferMap // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType G2C_Benchmark
message C2G_Benchmark // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Benchmark // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


//////////////////////角色相关////////////////////////////////////////



message RoleInfoProto 
{
	int64 Id = 1;
	string Name = 2;
	int32 State = 3;
	string AccountName = 4;
	int64 LastLoginTime = 5;
	int64 CreateTime = 6;
	int32 ServerId = 7;
	int32 ConfigId = 8;
}



// ResponseType R2C_GetRoles
message C2R_GetRoles // ISessionRequest
{	
	//获得某个服务器的角色列表
	int32 RpcId = 1; 
	string Token = 2;
	string AccountName = 3;
	int32 ServerId = 4;
}

message R2C_GetRoles // ISessionResponse
{	
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated RoleInfoProto RoleInfoList = 4;
}

// ResponseType R2C_CreateRole
message C2R_CreateRole // ISessionRequest
{	
	//根据服务器id创建角色
	int32 RpcId = 1; 
	string Token = 2;
	string AccountName = 3;
	string Name = 4;
	int32 ServerId = 5;
	int32 ConfigId = 6;
}

message R2C_CreateRole // ISessionResponse
{	
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	RoleInfoProto RoleInfo = 4;
}

// ResponseType R2C_DeleteRole
message C2R_DeleteRole // ISessionRequest
{	
	//根据服务器id删除角色
	int32 RpcId = 1; 
	string Token = 2;
	string AccountName = 3;
	int64 RoleInfoId = 4;
	int32 ServerId = 5;
}

message R2C_DeleteRole // ISessionResponse
{	
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 DeleteRoleInfoId = 4;
}

//////////////////////角色相关////////////////////////////////////////


//////////////////////登陆相关////////////////////////////////////////

// ResponseType R2C_LoginAccount
message C2R_LoginAccount // ISessionRequest
{
	//登录并且获取token
	int32 RpcId = 1;
	string AccountName = 2;
	string Password = 3;
}

message R2C_LoginAccount // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string Token = 4;
}

message A2C_Disconnet // ISessionMessage
{
	//强制客户端session离线 0踢人 1超时
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message ServerInfoProto 
{
	//服务器列表数据
	int32 Id = 1;
	int32 Status = 2;
	string ServerName = 3;
}

// ResponseType R2C_GetServerInfos
message C2R_GetServerInfos // ISessionRequest
{	
	//获得服务器列表
	int32 RpcId = 1; 
	string Token = 2;
	string AccountName = 3;
}

message R2C_GetServerInfos // ISessionResponse
{	
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated ServerInfoProto ServerInfoList = 4;
}


// ResponseType R2C_GetRealmKey
message C2R_GetRealmKey // ISessionRequest
{	
	//获得realm服务器的key
	int32 RpcId = 1; 
	string Token = 2;
	string AccountName = 3;
	int32 ServerId = 4;
}

message R2C_GetRealmKey // ISessionResponse
{	
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string Address = 4;
	int64 Key = 5;
	int64 GateId = 6;
}


// ResponseType G2C_LoginGameGate
message C2G_LoginGameGate // ISessionRequest
{
	//账号登录GameGate
	int32 RpcId = 1;
	int64 Key = 2; // realmkey
	string AccountName = 3; // 帐号
	int64 RoleId = 4; //角色id
	int32 ConfigId = 5; //初始角色配置id
	string Name = 6;//角色名字
}

message G2C_LoginGameGate // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}

// ResponseType G2C_EnterGame
message C2G_EnterGame // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_EnterGame // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	/// 自己的UnitId
	int64 MyUnitId = 4;
}

//////////////////////登陆相关////////////////////////////////////////

//////////////////////数值///////////////////////////////////////////

// ResponseType M2C_TestNumericValue
message C2M_TestNumericValue // ILocationRequest
{
	int32 RpcId = 1;
}

message M2C_TestNumericValue // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string response = 4;
}

message M2C_NoticeUnitNumeric // IMessage
{
	int64 UnitId = 1;
	int32 NumericType = 2;
	int64 NewValue = 3 ;
}

message M2C_NoticeNumericMsg // IMessage
{
	int32 NumericType = 1;
	int64 NewValue = 2;
}

message M2C_NoticeUnitNumericList // IMessage
{
	int64 UnitId = 1;
	repeated int32 NumericTypeList = 2;
	repeated int64 NewValueList = 3;
}

//////////////////////数值///////////////////////////////////////////
//////////////////////背包///////////////////////////////////////////
message ItemProto
{
	int32 ConfigId = 1;
	int32 ContainerType = 2;
	int64 Id = 3;
	int32 Count = 4;
	int32 ItemQuality  = 5;
	EquipInfoProto EquipInfo = 6;
}

message M2C_UpdateItemInfo // IMessage
{
	int32 Op = 1;
	ItemProto ItemInfo = 2;
}

// ResponseType M2C_GetAllKnapsack
message C2M_GetAllKnapsack // ILocationRequest
{
	int32 RpcId = 1;
}

message M2C_GetAllKnapsack // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated ItemProto ItemList = 4;
}

// ResponseType M2C_AddKnapsackItem
message C2M_AddKnapsackItem // ILocationRequest
{
	int32 RpcId = 1;
	int32 ContainerType = 2;
	int32 ConfigId = 3;
}

message M2C_AddKnapsackItem // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType M2C_RemoveKnapsackItem
message C2M_RemoveKnapsackItem // ILocationRequest
{
	int32 RpcId = 1;
	int32 ContainerType = 2;
	int64 ItemId = 3;
}

message M2C_RemoveKnapsackItem // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message M2C_SyncAllKnapsackItems // IMessage
{
	repeated ItemProto ItemList = 1;
}

message AttributeEntryProto
{
	int64 Id = 1;
	int32 Key = 2;
	int64 Value = 3;
	int32 EntryType = 4;
}


message EquipInfoProto
{
	int64 Id    = 1;
	int32 Score = 2;
	repeated AttributeEntryProto AttributeEntryProtoList = 3;
}

//////////////////////背包///////////////////////////////////////////
//////////////////////排行榜///////////////////////////////////////////
message RankInfoProto
{
	int64 Id      = 1;
	int64 UnitId  = 2;
	string Name   = 4;
	int64  RankValue  = 5;
}

//ResponseType Rank2C_GetRanksInfo
message C2Rank_GetRanksInfo // IRankInfoRequest
{
	int32 RpcId        = 1;
}


message Rank2C_GetRanksInfo // IRankInfoResponse
{
	int32 RpcId    = 1;
	int32 Error    = 2;
	string Message = 3;
	repeated RankInfoProto RankInfoProtoList = 4;
}
//////////////////////排行榜///////////////////////////////////////////

//////////////////////邮件///////////////////////////////////////////
message MailInfoProto
{
	int64 MailId = 1;
	int32 ConfigId = 2;
	string Title = 3;
	string Message = 4;
	repeated ItemProto RewardList = 5;
	bool IsRead = 6;
	bool IsCollected = 7;
}

//ResponseType Mail2C_GetAllMailList
message  C2Mail_GetAllMailList // IMailInfoRequest
{
	int32 RpcId        = 1;
}

message Mail2C_GetAllMailList // IMailInfoResponse
{
	int32 RpcId    = 90;
	int32 Error    = 91;
	string Message = 92;
	repeated MailInfoProto MailInfoList = 1;
}

message Mail2C_NewMail // IMessage
{
	MailInfoProto MailInfo = 1;
}

//ResponseType Mail2C_CollectAttachment
message C2Mail_CollectAttachment // IMailInfoRequest
{
	int32 RpcId        = 1;
	int64 MailId = 2;
}

message Mail2C_CollectAttachment // IMailInfoResponse
{
	int32 RpcId    = 1;
	int32 Error    = 2;
	string Message = 3;
}



message Mail2C_UpdateMailInfo // IMessage
{
	MailInfoProto MailInfo = 1;
}

message C2Mail_ReadMail // IMailInfoMessage
{
	int64 MailId = 1;
}




//////////////////////邮件///////////////////////////////////////////

//////////////////////组队///////////////////////////////////////////
// ResponseType G2C_CreateTeam
message C2G_CreateTeam // ISessionRequest
{
	int32 RpcId = 1;
	string TeamName = 2;//队伍名
}

message G2C_CreateTeam // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType G2C_LeaveTeam
message C2G_LeaveTeam // ISessionRequest
{
	int32 RpcId = 1;
	int64 Dissolve = 2;
}

message G2C_LeaveTeam // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

//////////////////////组队///////////////////////////////////////////
//////////////////////技能///////////////////////////////////////////
//cast开头
// ResponseType M2C_CastStart
message C2M_CastStart // ILocationRequest
{
	int32 RpcId = 1;
	int32 CastConfigId = 2;//技能配表id
	Unity.Mathematics.float3 InputPos = 3;//输入坐标
	int64 InputUnitId = 4;//目标对象id
}

//cast回调
message M2C_CastStart // ILocationResponse
{
  	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 CastId = 4;//技能uuid
	int64 CasterId = 5;//释放者id
	int32 CastConfigId = 6;//技能配置表id
	repeated int64 TargetsId = 7;//所有目标
}
//cast结束
message M2C_CastFinish // IMessage
{
	int64 CastId = 1;//技能uuid 
	int64 CasterId = 2;//释放者id
}
//cast打断
message M2C_CastBreak // IMessage
{
	int64 CastId = 1;//技能uuid 
	int64 CasterId = 2;//释放者id
}
//cast命中
message M2C_CastHit // IMessage
{
	int64 CastId = 1;//技能uuid 
	int64 CasterId = 2;//释放者id
	repeated int64 TargetsId = 3;//所有目标
}

//////////////////////技能///////////////////////////////////////////


//////////////////////Buff///////////////////////////////////////////
//buff
message BuffProto 
{
	int64 Id = 1;
	int32 ConfigId = 2;
	int64 ExpireTime = 3;
	int64 CreateTime = 4;
	byte[] ExtraData = 5;
}
//buff添加
message M2C_BuffAdd // IMessage
{
	int64 UnitId = 1;
	BuffProto BuffData = 2;
}
//buff迭代
message M2C_BuffTick // IMessage
{
  	int64 UnitId = 1;
	int64 BuffId = 2;
}
//buff更新
message M2C_BuffUpdate // IMessage
{
    int64 UnitId = 1;
	BuffProto BuffData = 2;
}
//buff移除
message M2C_BuffRemove // IMessage
{
    int64 UnitId = 1;
	int64 BuffId = 2;
}
//////////////////////Buff///////////////////////////////////////////

//////////////////////相关GM///////////////////////////////////////////
// ResponseType Mail2C_GMAddMail
message C2Mail_GMAddMail // IMailInfoRequest
{
	int32 RpcId = 1;
	int32 ConfigId = 2;
}

message Mail2C_GMAddMail // IMailInfoResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

//////////////////////相关GM///////////////////////////////////////////