//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using TEngine;
using UnityEngine;

namespace GameLogic
{
    [DisallowMultipleComponent]
    public partial class UIBindComponent : MonoBehaviour
    {
        [SerializeField] private List<UnityEngine.Object> m_components = new List<UnityEngine.Object>();

        public int ComponentCount => m_components.Count;

        public GameObject GetGameObject(int index)
        {
            if (index < 0 || index >= m_components.Count)
            {
                Log.Error("索引超出范围");
                return null;
            }

            UnityEngine.Object reference = m_components[index];
            if (reference is GameObject gameObject)
            {
                return gameObject;
            }

            if (reference is Component component)
            {
                return component.gameObject;
            }

            Log.Error($"索引 {index} 不是有效的 GameObject 引用");
            return null;
        }

        public T GetComponent<T>(int index) where T : Component
        {
            if (index < 0 || index >= m_components.Count)
            {
                Log.Error("索引超出范围");
                return null;
            }

            UnityEngine.Object reference = m_components[index];
            if (reference is T component)
            {
                return component;
            }

            if (reference is GameObject gameObject)
            {
                T c = gameObject.GetComponent<T>();
                if (c == null)
                {
                    Log.Error($"没有找到对应类型: {typeof(T).FullName}");
                }

                return c;
            }

            Log.Error($"没有找到对应类型: {typeof(T).FullName}");
            return null;
        }
    }
}